### PR TITLE
add-language-support

### PR DESCRIPTION
**Pull request by derunterstrich**
Add language support.

### CODE REVIEW

**Comment by johannschopplich** [comment]
Thank you for your contribution! I've made some suggestions. 🙂

**Comment by derunterstrich** [comment]
Thanks and I apologize for the stupid question, I'm usually on GitLab, but I can't find your suggestions.

**Comment by johannschopplich** [comment]
You should see them right above my last comment. Or, you can switch into the file changes tab.

grafik

**Comment by johannschopplich** [comment]
My bad, didn't request the review…

**Review by johannschopplich — CHANGES_REQUESTED** [review]

**Pull request closed without merging**
